apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "longrunningjob:blueshoe.de:operator"
  namespace: "kubecom"
rules:
  - apiGroups: ["blueshoe.de"]
    resources: ["longrunningjobs"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "deployments:operator"
  namespace: "kubecom"
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["pods", "jobs", "deployments"]
    verbs: ["*"]