apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: longrunningjobs.blueshoe.de
spec:
  group: blueshoe.de
  names:
    kind: LongRunningJob
    listKind: LongRunningJobList
    singular: longrunningjob
    plural: longrunningjobs
    shortNames:
      - lrj
      - lrjs
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
